### ISSUE TITLE
Register on packagist.org

### ISSUE THREAD

**Issue by Gounlaf** [philipnorton42/PHP-Password#4]
Hi,

is it possible to register your library on packagist ?
Explainations are provided here : https://github.com/philipnorton42/PHP-Password/settings/hooks

Thanks

**Comment by philipnorton42** [comment]
Done! :) https://packagist.org/packages/philipnorton42/php-password
Thanks for the suggestion.

**Comment by Gounlaf** [comment]
Hi @philipnorton42,

Thanks
