### ISSUE TITLE
Generated password is +1 of every length.

### ISSUE THREAD

**Issue by unnaki** [philipnorton42/PHP-Password#5]
The `generatePassword` method seems to generate a password with 1 extra element for every length specified.
Using this options:

    [
        'minLength'      => 8,
        'maxLength'      => 30,
        'minNumbers'     => 2,
        'minLetters'     => 5,
        'minLowerCase'   => 3,
        'minUpperCase'   => 2,
        'minSymbols'     => 1,
        'maxSymbols'     => 1,
        'allowedSymbols' => array('#', '_', '-', '!', '[', ']', '=', '~', '*'),
    ]

This are some password generated with such options:

**D69Vh9n~Ljn=**
**E9u_LaU_eu96**
**_rt47M6hdZS=**

Of course, every single one fails.

**Comment by philipnorton42** [comment]
Thanks for reporting this. I've pushed a fix and a test. Let me know if you get any more issues :)
